// This file was automatically generated by VS extension Windows Machine Learning Code Generator v3
// from model file model_float32_lightning.onnx
// Warning: This file may get overwritten if you add add an onnx file with the same name
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Windows.Media;
using Windows.Storage;
using Windows.Storage.Streams;
using Windows.AI.MachineLearning;
namespace WinML_MoveNet
{
    
    public sealed class model_float32_lightningInput
    {
        public TensorFloat input00; // shape(1,192,192,3)
    }
    
    public sealed class model_float32_lightningOutput
    {
        public TensorFloat Identity; // shape(1,1,17,3)
    }
    
    public sealed class model_float32_lightningModel
    {
        private LearningModel model;
        private LearningModelSession session;
        private LearningModelBinding binding;
        public static async Task<model_float32_lightningModel> CreateFromStreamAsync(IRandomAccessStreamReference stream)
        {
            model_float32_lightningModel learningModel = new model_float32_lightningModel();
            learningModel.model = await LearningModel.LoadFromStreamAsync(stream);
            learningModel.session = new LearningModelSession(learningModel.model);
            learningModel.binding = new LearningModelBinding(learningModel.session);
            return learningModel;
        }
        public async Task<model_float32_lightningOutput> EvaluateAsync(model_float32_lightningInput input)
        {
            binding.Bind("input:0", input.input00);
            var result = await session.EvaluateAsync(binding, "0");
            var output = new model_float32_lightningOutput();
            output.Identity = result.Outputs["Identity"] as TensorFloat;
            return output;
        }
    }
}

